server:
    port: 8080

spring:
    cloud:
        gateway:
            discovery.locator.enabled: true
            routes:
                -   id: user_service_route
                    uri: lb://user-service
                    predicates:
                        - Path=/admin/users/**
                -   id: request_service_route
                    uri: lb://request-service
                    predicates:
                        - Path=/users/*/requests/**

