eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        instance:
            preferIpAddress: true
            hostname: localhost
            instance-id: "${spring.application.name}:${random.value}"
            leaseRenewalIntervalInSeconds: 10

spring:
    application:
        name: stats-service

